# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-26 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('gradeid', models.IntegerField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(blank=True, max_length=20, null=True)),
                ('press', models.CharField(blank=True, max_length=30, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TClazz',
            fields=[
                ('clazzid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('clazzname', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_clazz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TCourse',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TStudent',
            fields=[
                ('studentid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('studentname', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TStuentCourse',
            fields=[
                ('xkid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't_stuent_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTeacher',
            fields=[
                ('teacherid', models.IntegerField(primary_key=True, serialize=False)),
                ('teachername', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTeacherCourse',
            fields=[
                ('rkid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't_teacher_course',
                'managed': False,
            },
        ),
    ]
