# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-26 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('gradeid', models.IntegerField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(blank=True, max_length=20, null=True)),
                ('press', models.CharField(blank=True, max_length=30, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TClazz',
            fields=[
                ('clazzid', models.IntegerField(primary_key=True, serialize=False)),
                ('clazzname', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_clazz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TCourse',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TStudent',
            fields=[
                ('studentid', models.IntegerField(primary_key=True, serialize=False)),
                ('studentname', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TStuentCourse',
            fields=[
                ('xkid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't_stuent_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTeacher',
            fields=[
                ('teacherid', models.IntegerField(primary_key=True, serialize=False)),
                ('teachername', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTeacherCourse',
            fields=[
                ('rkid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't_teacher_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cname', models.CharField(max_length=20, unique=True, verbose_name='\u5206\u7c7b\u540d\u79f0')),
            ],
            options={
                'db_table': 'blog_category',
                'verbose_name_plural': '\u5206\u7c7b\u7ba1\u7406\u8868',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=20, verbose_name='\u6807\u9898')),
                ('desc', models.TextField(verbose_name='\u7b80\u4ecb')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('created', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Category', verbose_name='\u5206\u7c7b\u8be6\u60c5')),
            ],
            options={
                'db_table': 'blog_post',
                'verbose_name_plural': '\u5e16\u5b50\u7ba1\u7406\u8868',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tname', models.CharField(max_length=20, unique=True, verbose_name='\u6807\u7b7e\u540d\u79f0')),
            ],
            options={
                'db_table': 'blog_tag',
                'verbose_name_plural': '\u6807\u7b7e\u7ba1\u7406\u8868',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='student.Tag', verbose_name='\u53ef\u9009\u6807\u7b7e'),
        ),
    ]
